
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.




import UIKit

func evenFibonacciNumbers(max: Int) -> Int {
    var num1 = 0
    var num2 = 1
    var temp = 0
    var sum = 0
    
    while num2 < 4000000 {
        if num2 % 2 == 0 {
            sum = sum + num2
        }
        
        temp = num1 + num2;
        num1 = num2;
        num2 = temp;
    }
    return sum
}


print(evenFibonacciNumbers(max: 4000000))
